name       : espeak-ng
version    : 1.49.2
release    : 3
source     :
    - https://github.com/espeak-ng/espeak-ng/archive/1.49.2.tar.gz : a2ac11ee20130388f58c829b10dfba7f496e83e89ebe5460d1bae06a36a1c5be
license    :
    - GPL-3.0
    - BSD-2-Clause
component  : programming.library
summary    : Text-to-speech engine
description: |
    Next generation text-to-speech engine, a fork of espeak.
builddeps  :
    - pcaudiolib-devel
setup      : |
    %autogen
    %configure --with-pcaudiolib \
               --with-klatt \
               --with-mbrola \
               --with-async \
               --disable-static
build      : |
    %make -j1
install    : |
    %make_install -j1
    # symlink buggery
    rm -v $installdir/%libdir%/*.la
