name       : espeak-ng
version    : 1.49.0
release    : 1
source     :
    - https://github.com/espeak-ng/espeak-ng/archive/1.49.0.tar.gz : c7ef98b5bf86ffc00cde8930fc7a2182826d82ea183a03c85b24218c30eaddb2
license    :
    - GPL-3.0
    - BSD-2-Clause
component  : programming.library
summary    : Text-to-speech engine
description: |
    Next generation text-to-speech engine, a fork of espeak.
builddeps  :
    - pcaudiolib-devel
setup      : |
    %autogen
    %configure --with-pcaudiolib \
               --with-klatt \
               --with-mbrola \
               --with-async \
               --disable-static
build      : |
    %make -j1
install    : |
    %make_install -j1
    # symlink buggery
    rm -v $installdir/%libdir%/*.la
